### ISSUE TITLE
生成density map的delta值是多少？

### ISSUE THREAD

**Issue by LaiPiXiong** [BIGKnight/SANet_implementation#5]
请问一下你的密度图是怎么生成的呢？我的运行结果和你的一样，对于所有输入的image都倾向于输出固定的结果（0）。你的这种情况有没有得到改善呢？后来是怎么解决的呢？

**Comment by BIGKnight** [comment]
对不起,之前有其他事没有关注github, 不好意思没看到你的问题, 
我后来是放弃了这个网络了,  密度图的话应该问题, 我设定的高斯半径为15, 实现都是按着CSRNet的源码来的. 输出是0的话是因为某层网络输出都为0了, 导致整个网络后向通过relu的时候跟新不了了. 原因是因为如果直接norm接relu, norm后负数太多 导致无效输出太多, 层数一深就死. 我试了lrelu,效果依然很差, 但是不会趋于0了.
后来老师和我说normalization后要线性变换后再送relu(貌似这个是常识,,,,我太菜了所以之前一直不知道./(ㄒoㄒ)/~~), 但是由于临近春节, 节后在准备托福就一直没有弄了. 现在基本上放弃这个网络结构了,额你可以再去问问作者.
